### ISSUE TITLE
streaming demo doesn't work

### ISSUE THREAD

**Issue by nivertech** [oanda/streamingapi-demo#1]

**Comment by ghost** [comment]
They just turned if off. And as far as I know they do plan to release initial REST version without a streaming rates.  What a shame...

**Comment by cyip** [comment]
We turned off streaming rates mainly due to performance issues with our new sandbox hardware.  Streaming rate is still in experimental stage.  Thank you for all the feedback on this.

**Comment by fahmad91** [comment]
When will the streaming API be available? Is there something else we can use as a replacement so that I can continue with the development of my trading system? Maby something that only works on a practice account?

**Comment by abendigo** [comment]
This has been resolved with the latest commit
